### ISSUE TITLE
pkg version conflicts

### ISSUE THREAD

**Issue by zhxiaokang** [NahyeKim/DeepBE#1]
The required versions of `python==3.6.13` and `pandas==1.3.0` are conflicted since `pandas==1.3.0` requires `python>=3.7`, as reported by `Conda`.

I also tried to install `pandas==1.3.0` by `pip`, but the latest available version is `1.1.5` (on date 19/6/2023)

**Comment by moloch12** [comment]
Hi, I also encountered this problem, and even after I installed the appropriate version, the model file still wouldn't load. Any suggestions? 

Traceback (most recent call last):
  File "/public/home/moloch/be/new_analysis/ad_f3/deepbe/DeepBE/YE1-BE4max/DeepBE_YE1.py", line 9, in <module>
    final_model =  tf.keras.models.load_model('DeepBE_YE1_model',compile=False)
  File "/public/home/moloch/miniconda3/envs/py1/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/public/home/moloch/miniconda3/envs/py1/lib/python3.10/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 66, in get_tensor
    return CheckpointReader.CheckpointReader_GetTensor(
IndexError: Read less bytes than requested

**Comment by NahyeKim** [comment]
@sungchulc Could you please help with this?

**Comment by zhxiaokang** [comment]
> 

Hi @moloch12 , after struggling with the environment and version issue for several days, I suddenly succeeded for once with even "inappropriate" verions of CUDA (12.0) and tensorflow (2.12.0). But it didn't work the next day.

It seems that the real reason behind your error `IndexError: Read less bytes than requested` (I also had the same and kept questioning about my environment setting) is because the model file cannot be fetched from [LFS ](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage)(the one in the repo `*model/variables/variables.data-00000-of-00001` is just a pointer to a large file in the LFS), since the repository's data quota is used up, as I reported in this [issue](https://github.com/NahyeKim/DeepBE/issues/2).

So as long as [Issue 2](https://github.com/NahyeKim/DeepBE/issues/2) is resolved, your problem should be solved.

**Comment by sungchulc** [comment]
Hi guys I'll take a look at this issue and the issue 2 in a few days and get back to you guys.
We'll recheck if LFS payment is up to date and if it still doesn't work, we'll try to provide an alternative way to download our models in a few days. Thanks

**Comment by moloch12** [comment]
> @sungchulc Could you please help with this?

Thanks for developing this brilliant tool! I have tried your web version which is easy to use. However, I met this error which returns nothing
```
A PHP Error was encountered
Severity: Warning

Message: file_get_contents(data/77c6c908a69e5472d15e569964e206b2a1a2240f/DeepBE_Results.txt): failed to open stream: No such file or directory

Filename: views/result1.php

Line Number: 8

Backtrace:

File: /home/snusry/DeepCpf1/DeepBE/application/views/result1.php
Line: 8
Function: file_get_contents

File: /home/snusry/DeepCpf1/DeepBE/application/controllers/Job.php
Line: 210
Function: view

File: /home/snusry/DeepCpf1/DeepBE/index.php
Line: 315
Function: require_once
```
I would appreciate it if you and your team could fix the error. 
Best.

**Comment by sungchulc** [comment]
@moloch12 
We believe that there has been some temporary unknown error at that time,, maybe possibly due to high traffic..
With the same sequence and options that you chose, we confirmed that the webtool was working (URL: http://deepcrispr.info/DeepBE/page/user/bf78f0316937a2d813858dd738513f6d009902ed). Please run it again and let us know if it works.

Also, please open new issues for errors that are not related to this current issue.
Thanks

**Comment by moloch12** [comment]
> @moloch12 We believe that there has been some temporary unknown error at that time,, maybe possibly due to high traffic.. With the same sequence and options that you chose, we confirmed that the webtool was working (URL: http://deepcrispr.info/DeepBE/page/user/bf78f0316937a2d813858dd738513f6d009902ed). Please run it again and let us know if it works.
> 
> Also, please open new issues for errors that are not related to this current issue. Thanks

Thank you. On my second try, it worked, and it looks like it was caused by the Internet. This tool is very robust and a simple refresh will work like a charm.
Best.

**Comment by sungchulc** [comment]
I've just published a new release for the model files (codes are the same) since they are downloaded as git lfs pointers rather than actual files.
Please download files model_v1a to j from the release note and merge/untar them for use.

Since the package versions used for development is quite outdated, I also checked if the models are runnable with the newer package versions. The models were runnable with the current google colab package versions as below.

TF = 2.12.0
Python = 3.10.12
Numpy = 1.22.4
Pandas = 1.5.3
cuda = 11.8
cudnn = 8.9

If there's still a problem with the model files or package versions, please let me know.
Thanks
