### ISSUE TITLE
Data quota used up

### ISSUE THREAD

**Issue by zhxiaokang** [NahyeKim/DeepBE#2]
Hi, the model files stored in *model/variables cannot be fetched, as the error message says `batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

**Comment by NahyeKim** [comment]
@sungchulc Could you please help with this?

**Comment by sungchulc** [comment]
I've just published a new release for the model files (codes are the same) since they are downloaded as git lfs pointers rather than actual files.
Please download files model_v1a to j from the release note and merge/untar them for use.

Since the package versions used for development is quite outdated, I also checked if the models are runnable with the newer package versions. The models were runnable with the current google colab package versions as below.

TF = 2.12.0
Python = 3.10.12
Numpy = 1.22.4
Pandas = 1.5.3
cuda = 11.8
cudnn = 8.9

If there's still a problem with the model files or package versions, please let me know.
Thanks
